### PR TITLE
Start Strapi in dev mode with --watch-admin option

### PR DESCRIPTION
**Pull request by Phu2**
Not tested yet (as i don't know how to test ...) but you might give it a try nonetheless.

### CODE REVIEW

**Comment by fsteeg** [comment]
Thanks for looking into this! I did a docker compose `build`, but then after the `up`, there is no link to the admin UI at http://localhost:1339, and http://localhost:1339/admin gives a 404. I also tried http://localhost:8000/admin (8000 is added in this PR?), where I get a popup error from Strapi and the page seems to keep on loading (spinning icon in the middle).

**Comment by Phu2** [comment]
Discussed offline, nothing to do with the `.env` file.
 
After that i tried to build a new docker image via `sudo docker compose up --build` but ran into an error when `npm install` is issued:

```
426.2 npm ERR! request to https://registry.npmjs.org/@notum-cz%2fstrapi-plugin-content-versioning failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
```
It looks like npm is not able to reach the registry inside the container. As a workaround use the host network during docker build: `sudo docker build -f Dockerfile.dev -t strapi-rpb . --network=host`

Finally, `sudo docker compose up` starts strapi with the `--watch-admin` option:
```
strapi-rpb    | > strapi@0.1.0 develop
strapi-rpb    | > strapi develop --watch-admin
strapi-rpb    | 
strapi-rpb    | Starting the development server...
strapi-rpb    | 
strapi-rpb    | Admin development at http://localhost:8000/admin/
```
but the page at http://localhost:8000/admin first shows a message "Warning: an error occurred while requesting the API" then keeps loading. Now i can reproduce the behaviour.. needs further investigation.

**Comment by Phu2** [comment]
It's a CORS problem, screenshots from the developer console in firefox:
grafik
grafik

**Comment by Phu2** [comment]
In order to keep the configurations simple just get rid of the custom port mapping (`1339:1337`) in order to prevent the problem with CORS.

**Comment by Phu2** [comment]
@fsteeg Please try again (if needed).

**Review by fsteeg — APPROVED** [review]
Thanks! Pushed update to README and some config changes required to make the lookup plugin work with the new setup. Looks good, and now automatically reloads during plugin development. :+1:

**Pull request merged**
