### PR TITLE
Write result data to disk in `afterCreate` and `afterUpdate` hooks

### PR DESCRIPTION
**Pull request by fsteeg**
This is an approach to address the backup topic we discussed in our last RPB meeting after the recent accidental deletions (see bottom of page):

https://service-wiki.hbz-nrw.de/display/SEM/2024-06-20+RPB-Treffen

Basic idea: to avoid losing data that has been entered after the last regular backup (and instead of setting up frequent e.g. hourly exports), we write every edit to disk.

@Phu2 Does the approach make sense to you? In dev mode it seems to work fine, files appear outside of the container in `backup/`. In prod mode, they don't show up (only inside the container, see test system). I added the same volume mapping as in dev, but that's probably not the right way to do it?

If we do take this approach, we should clean up the files in `backup` automatically (e.g. delete all from before the last full backup / export), and maybe copy them to another server / location additionally, like the exports?

(Only implemented for persons here, would add for articles and independent-works if we keep it.)

### CODE REVIEW

**Comment by Phu2** [comment]
> In prod mode, they don't show up (only inside the container, see test system). I added the same volume mapping as in dev, but that's probably not the right way to do it?

The volume was just added to the wrong container, fixed by https://github.com/hbz/strapi-rpb/pull/36/commits/de9c24e574f7b54ef2d0b391cf7642814156f616

**Comment by Phu2** [comment]
> If we do take this approach, we should clean up the files in backup automatically (e.g. delete all from before the last full backup / export), and maybe copy them to another server / location additionally, like the exports?

We could save the edits to a dedicated subdirectory `/opt/app/backup/edits`.

We should then replace the current cronjobs by a new backup script which should do these things:

1. run `strapi export` inside the container (save to `/opt/app/backup/export`)
2. stop strapi
3. copy `./backup/{export,edits}` on the host to a another server && delete `./backup/{export,edits}` 
4. restart strapi

**Comment by Phu2** [comment]
> Basic idea: to avoid losing data that has been entered after the last regular backup (and instead of setting up frequent e.g. hourly exports), we write every edit to disk.

> Does the approach make sense to you? 

Pros: 

- every edit is saved unless we delete the backup; thus we (admins) are able to restore accidental deletions

Contra:

- it's opaque to users, items are not really deleted even if they meant to be deleted
- users cannot restore on their own

I'm okay with this approach. It's simple and light-weight, i think.

Not sure if we still should take a look into "soft delete" aka trash bin. There is a [plugin](https://market.strapi.io/plugins/strapi-plugin-soft-delete) and a [tutorial](https://strapi.io/blog/custom-soft-delete-with-strapi-and-next-js-14-building-a-recycle-bin).

**Comment by fsteeg** [comment]
> The volume was just added to the wrong container, fixed by https://github.com/hbz/strapi-rpb/commit/de9c24e574f7b54ef2d0b391cf7642814156f616

Ah, yes, that's why that looked so different, should have double-checked. Thanks! Now it works as expected on the test system.

> We could save the edits to a dedicated subdirectory `/opt/app/backup/edits`
> [...] run `strapi export` inside the container (save to `/opt/app/backup/export`)

Currently the export is not saved to that location right? Looking at the crontab it's `/backup/strapi-rpb/`. If you prefer to store both in the same location that would be fine with me, but from my point of view we would not have to change the export location. Also, the export is copied in the crontab for transformation and indexing in the Web-OPAC. If there is no need, I don't think we should touch the export workflow at all for this issue.

> copy `./backup/{export,edits,database}` on the host to a another server && delete `./backup/{export,edits,database}`

Ah, right, this is where it's connected to the export. Once the export is done, the old edit-backups are no longer needed. So I guess this should be a safe way (to avoid losing edits made during the export):

1. Move edits to a temp folder
2. Run export
3. Delete temp folder it it worked

We can skip copying the edits to another server at this point, because we have the full export. To create another level of security for the edits, we'd have to copy them elsewhere much more often than the export, but maybe that's overkill, as this is more of a measure against accidental deletion, not server failure (for which we have the exports).

> Not sure if we still should take a look into "soft delete" aka trash bin. There is a [plugin](https://market.strapi.io/plugins/strapi-plugin-soft-delete) and a [tutorial](https://strapi.io/blog/custom-soft-delete-with-strapi-and-next-js-14-building-a-recycle-bin).

Ah, interesting. Added that to the possible options in the meeting notes linked above.

**Comment by fsteeg** [comment]
Even with just the current state, we'd have the additional security against data loss, and it would take quite a while to become a relevant amount of data, so I think we should deploy this to production. What do you think, @Phu2?

**Review by Phu2 — APPROVED** [review]

**Comment by Phu2** [comment]
> Even with just the current state, we'd have the additional security against data loss, and it would take quite a while to become a relevant amount of data, so I think we should deploy this to production. What do you think, @Phu2?

+1

**Pull request merged**
