### PR TITLE
Add autocomplete plugin and theme

### PR DESCRIPTION
**Pull request by Phu2**
These packages are required.

### CODE REVIEW

**Comment by fsteeg** [comment]
They are already in the plugin's [package.json](https://github.com/hbz/strapi-rpb/blob/main/src/plugins/lookup/package.json), are they really required in the root as well? Did you run `npm install` in the plugin directory (see https://github.com/hbz/strapi-rpb#plugin)?

**Comment by Phu2** [comment]
I see. You may want to automatically install the lookup plugin during docker setup? See my other PR https://github.com/hbz/strapi-rpb/pull/10
For the deployment of the production instance i have included this step in the Dockerfile already.

**Comment by fsteeg** [comment]
> You may want to automatically install the lookup plugin during docker setup? See my other PR #10

Ah yes, great, didn't think about that!

**Comment by Phu2** [comment]
Packages are already included in the plugin directory. Closing.

**Pull request closed without merging**
