### PR TITLE
Inject link list button in `listView` `actions` zone (RPB-183)

### PR DESCRIPTION
**Pull request by fsteeg**
See https://jira.hbz-nrw.de/browse/RPB-183

Build links to Strapi edit view for each item in list.

Display as links in HTML page.

### CODE REVIEW

**Comment by fsteeg** [comment]
Deployed to test, see e.g.:

https://rpb-cms-test.lobid.org/admin/content-manager/collectionType/api::article.article?page=1&pageSize=10&sort=rpbId:ASC&filters[$and][0][updatedAt][$gt]=2024-08-24T22:00:00.000Z

Result of clicking button "Linkliste":

https://rpb-cms-test.lobid.org/admin/plugins/lookup/list/api::article.article/1537576,1537574

**Comment by acka47** [comment]
Looks good for a list of two or three resources. I see that the list URL contains the IDs of all resources on it, e.g. `https://rpb-cms-test.lobid.org/admin/plugins/lookup/list/api::article.article/1537572,1537576,1537574`. Will this scale if we have lists of e.g. two hundred resources?

I tried it with this list containing 565 entries: https://rpb-cms-test.lobid.org/admin/content-manager/collectionType/api::rpb-authority.rpb-authority?page=1&pageSize=50&sort=preferredName:ASC&filters[$and][0][preferredName][$contains]=Mainz

The resulting HTML contains only 50 entries: https://rpb-cms-test.lobid.org/admin/plugins/lookup/list/api::rpb-authority.rpb-authority/987402,820101,959988,969079,974683,987790,981319,987130,986619,966310,830434,953379,971702,960982,971562,995675,978217,985857,981314,985826,831130,971902,987307,987803,867565,867568,987812,820131,966928,820049,969064,959995,831144,828879,974168,979876,971867,983243,979864,974072,961209,963423,976367,953354,835792,969075,995659,831992,820052,974224

I am not sure whether this will suffice.

**Comment by fsteeg** [comment]
> The resulting HTML contains only 50 entries

It's based on the actual list visible in the Strapi UI, so you'll have to increase the number of items to display (bottom left). Max in Strapi is 100, so larger lists will have to be split up (e.g. by filtering for smaller date ranges).

**Comment by acka47** [comment]
Ah, I understand. So, let's try it out whether D.C. is happy with it. +1 from me.

**Review by acka47 — APPROVED** [review]

**Pull request merged**
